---
title: "R^3^: Entornos reproducibles para R"
author: "Jose Manuel Vera Oteo"
date: "25 de mayo de 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## La vida diaria de un usuario de R

- **"Nuevo proyecto: voy instalando paquetes según voy necesitando."**


## La vida diaria de un usuario de R

- "Nuevo proyecto: voy instalando paquetes según voy necesitando."
- **"No recuerdo cómo instalé aquella librería que necesito para este paquete."**

## La vida diaria de un usuario de R

- "Nuevo proyecto: voy instalando paquetes según voy necesitando."
- "No recuerdo cómo instalé aquella librería que necesito para este paquete."
- **"En windows el proceso es muy complicado (o no funciona)."**

## La vida diaria de un usuario de R

- "Nuevo proyecto: voy instalando paquetes según voy necesitando."
- "No recuerdo cómo instalé aquella librería que necesito para este paquete."
- "En windows el proceso es muy complicado (o no funciona)."
- **"¿Pasarlo a producción?. Claro. Muy fácil......."**

## La vida diaria de un usuario de R

- "Nuevo proyecto: voy instalando paquetes según voy necesitando."
- "No recuerdo cómo instalé aquella librería que necesito para este paquete."
- "En windows el proceso es muy complicado (o no funciona)."
- "¿Pasarlo a producción?. Claro. Muy fácil......."
- **"Feliz con PC nuevo hasta que caes que tienes que reinstalar y configurar todo."**

## La vida diaria de un usuario de R

- "Nuevo proyecto: voy instalando paquetes según voy necesitando."
- "No recuerdo cómo instalé aquella librería que necesito para este paquete."
- "Es que en windows es muy complicado (o no funciona)."
- "¿Pasarlo a producción?. Claro. Muy fácil......."
- "Feliz con PC nuevo: una semana hasta que todo queda igual que antes (o no)."
- **"¿compartimos el mismo entorno básico entre todo el departamento?"**
- **....y mi favorita......**

# "En mi equipo funciona".

## Soluciones habituales

- **Máquinas virtuales**

De gran tamaño, es muy complicado mover de un sitio a otro y además tienen 
requerimientos de computación exagerados. Es necesaria mucha memoria y cPU.

## Soluciones habituales

- Máquinas virtuales

- **Imágenes del disco**

Mismo problema que las máquinas virtuales pero magnificado. Las plantillas se
quedan obsoletas y hay que actualizarlas cada cierto tiempo.

## Soluciones habituales

- Máquinas virtuales

- Imágenes del disco

- **Documentarlo *TODO*.** 

 TODO->imagen de risas 

## Docker

### ¿qué es Docker?

### Wikipedia:
*"Docker es un proyecto de código abierto que automatiza el despliegue de aplicaciones dentro de contenedores de software, proporcionando una capa adicional de abstracción y automatización de Virtualización a nivel de sistema operativo en Linux.*

## Docker

### ¿Linux? ¿no lo puedo usar en Windows (o Mac OS)?

Si. Se puede usar en Windows con ciertas restricciones.

- Microsoft Hyper-V
- 64bit Windows 10 Pro, Enterprise / Education 

En Mac OS.

- Yosemite 10.10.3 o superior

Las habituales necesidades de hardware.

Aunque es siempre recomendable usar Linux. (no solo para Docker, sino en general)

## Docker


## Ventajas

- **Aislamiento**

No dependen del hardware ni del sistema operativo host.

## Ventajas

- Aislamiento
- **Portabilidad**

Permiten mover de manera sencilla el software de una máquina a otra.

## Ventajas

- Aislamiento
- Portabilidad
- **Sencillez**

Su uso es relativamente sencillo. Basta conocer 4 ó 5 comandos y unas nociones
muy básicas. Luego si queremos podemos profundizar.

## Ventajas

- Aislamiento
- Portabilidad
- Sencillez
- **Muy popular**

Aunque esto a veces alguien lo ve como una desventaja, en este caso nos
permite acceder a muchísima documentación o ayuda de manera sencilla.
Además hay imágenes para casi todo lo que nos imaginemos.

## Conceptos básicos:

- **contenedor**

Es la parte activa con la que interactuamos para obtener un resultado.

## Conceptos básicos:

- contenedor
- **imagen**

Es la plantilla en la que se basa el contenedor para saber lo que tiene que hacer.


## Conceptos básicos:

- contenedor
- imagen
- **registro**

Es el repositorio en el cual de manera abierta se ponen a disposición las imágenes.
Uno de los más conocidos y usados es "Docker Hub".

## Conceptos básicos:

- contenedor
- imagen
- registro
- **Dockerfile**

Es la "receta" para construir una imagen desde cero. Si conocéis Puppet o Chef 
se trata de un concepto similar.

## RECOMENDACIONES

- pocas capas
- contenedores con solamente una función


## CONCLUSIÓN

Ningún pinguino fué dañado en el curso de este trabajo

Source: https://www.docker.com/
